#!/bin/bash
set -e

folder=/tmp/iw-sub/
cleanup() {
    rm -rf $folder
}

trap 'cleanup' ERR
cleanup
mkdir -p $folder
cp -rf $1 $folder
cd $folder
unzip $(basename $1)
cd $(/bin/ls -d */ -t1 | head -n 1)

make clean
make
file cpp-iw | grep ELF >/dev/null && echo "De submissie voldoet aan de minimale vereisten" || echo "Geen uitvoerbaar bestand cpp-iw gevonden na uitvoeren van de Makefile."                                                           
